import type { Contact, Conversation, Message, Notification } from "./types"

export const CURRENT_USER: Contact = {
  id: "me",
  name: "Ama Owusu",
  phone: "+233 24 000 0000",
  bio: "Available",
  avatar: "https://ui-avatars.com/api/?name=Ama+Owusu&background=FFD600&color=000&bold=true",
  isOnline: true,
}

export const CONTACTS: Contact[] = [
  {
    id: "kwame",
    name: "Kwame Asante",
    phone: "+233 24 111 2233",
    bio: "Living life one day at a time",
    avatar: "https://ui-avatars.com/api/?name=Kwame+Asante&background=1a1a1a&color=FFD600&bold=true",
    isOnline: true,
  },
  {
    id: "zara",
    name: "Zara Mensah",
    phone: "+233 55 987 6543",
    bio: "Designer & dreamer",
    avatar: "https://ui-avatars.com/api/?name=Zara+Mensah&background=1a1a1a&color=FFD600&bold=true",
    isOnline: false,
  },
  {
    id: "kofi",
    name: "Kofi Boateng",
    phone: "+233 20 444 5566",
    bio: "Football is life ⚽",
    avatar: "https://ui-avatars.com/api/?name=Kofi+Boateng&background=1a1a1a&color=FFD600&bold=true",
    isOnline: true,
  },
  {
    id: "abena",
    name: "Abena Frimpong",
    phone: "+233 27 321 0987",
    bio: "Entrepreneur | Foodie",
    avatar: "https://ui-avatars.com/api/?name=Abena+Frimpong&background=1a1a1a&color=FFD600&bold=true",
    isOnline: false,
  },
  {
    id: "yaw",
    name: "Yaw Darko",
    phone: "+233 24 555 7788",
    bio: "Tech bro 🖥️",
    avatar: "https://ui-avatars.com/api/?name=Yaw+Darko&background=1a1a1a&color=FFD600&bold=true",
    isOnline: true,
  },
  {
    id: "efua",
    name: "Efua Asare",
    phone: "+233 50 222 3344",
    bio: "Peace and good vibes only ✌️",
    avatar: "https://ui-avatars.com/api/?name=Efua+Asare&background=1a1a1a&color=FFD600&bold=true",
    isOnline: false,
  },
]

export const CONVERSATIONS: Conversation[] = [
  {
    id: "conv-kwame",
    contact: CONTACTS[0],
    unreadCount: 2,
    lastMessage: "See you there! 🕒",
    lastTimestamp: "10:15 AM",
    messages: [
      { id: "m1", senderId: "me", text: "Yo Kwame! You free this evening?", timestamp: "9:41 AM", read: true },
      { id: "m2", senderId: "kwame", text: "Hey Ama! Yeah, what's up?", timestamp: "9:43 AM", read: true },
      { id: "m3", senderId: "me", text: "Thinking we could grab some jollof at that new spot?", timestamp: "9:44 AM", read: true },
      { id: "m4", senderId: "kwame", text: "Oh the one near Circle? 👀", timestamp: "9:45 AM", read: true },
      { id: "m5", senderId: "me", text: "Exactly! I heard their jollof is 🔥", timestamp: "9:46 AM", read: true },
      { id: "m6", senderId: "kwame", text: "Say less! What time?", timestamp: "10:12 AM", read: false },
      { id: "m7", senderId: "me", text: "See you there! 🕒", timestamp: "10:15 AM", read: false },
    ],
  },
  {
    id: "conv-zara",
    contact: CONTACTS[1],
    unreadCount: 0,
    lastMessage: "Perfect! I'll send over the designs tonight",
    lastTimestamp: "Yesterday",
    messages: [
      { id: "m1", senderId: "zara", text: "Hey Ama! Did you get the mood board I sent?", timestamp: "Yesterday 3:00 PM", read: true },
      { id: "m2", senderId: "me", text: "Yes Zara! It looks amazing 🤩", timestamp: "Yesterday 3:15 PM", read: true },
      { id: "m3", senderId: "zara", text: "Great! So should we go with option A or B?", timestamp: "Yesterday 3:20 PM", read: true },
      { id: "m4", senderId: "me", text: "Option B for sure! The colors pop more", timestamp: "Yesterday 3:25 PM", read: true },
      { id: "m5", senderId: "zara", text: "I knew you'd pick that one! 😊", timestamp: "Yesterday 3:30 PM", read: true },
      { id: "m6", senderId: "me", text: "When can we see the final designs?", timestamp: "Yesterday 3:35 PM", read: true },
      { id: "m7", senderId: "zara", text: "Perfect! I'll send over the designs tonight", timestamp: "Yesterday 4:00 PM", read: true },
    ],
  },
  {
    id: "conv-kofi",
    contact: CONTACTS[2],
    unreadCount: 3,
    lastMessage: "WE WON THE LEAGUE!!! 🏆🏆🏆",
    lastTimestamp: "Just now",
    messages: [
      { id: "m1", senderId: "kofi", text: "You watching the game?", timestamp: "7:00 PM", read: true },
      { id: "m2", senderId: "me", text: "Of course! Black Stars all the way 🖤⭐", timestamp: "7:05 PM", read: true },
      { id: "m3", senderId: "kofi", text: "This is intense!", timestamp: "8:30 PM", read: true },
      { id: "m4", senderId: "me", text: "Tell me about it! My heart is racing", timestamp: "8:35 PM", read: true },
      { id: "m5", senderId: "kofi", text: "GOAL!!! 🎉🎉🎉", timestamp: "8:45 PM", read: false },
      { id: "m6", senderId: "kofi", text: "Yes yes yes!!!", timestamp: "8:46 PM", read: false },
      { id: "m7", senderId: "kofi", text: "WE WON THE LEAGUE!!! 🏆🏆🏆", timestamp: "Just now", read: false },
    ],
  },
  {
    id: "conv-abena",
    contact: CONTACTS[3],
    unreadCount: 1,
    lastMessage: "Let's do brunch this weekend!",
    lastTimestamp: "2 hr ago",
    messages: [
      { id: "m1", senderId: "abena", text: "Hey Ama! How's business going?", timestamp: "10:00 AM", read: true },
      { id: "m2", senderId: "me", text: "It's going great! Thanks for asking", timestamp: "10:15 AM", read: true },
      { id: "m3", senderId: "abena", text: "That's wonderful! I have a new recipe I want to try", timestamp: "10:20 AM", read: true },
      { id: "m4", senderId: "me", text: "Oh really? What is it?", timestamp: "10:30 AM", read: true },
      { id: "m5", senderId: "abena", text: "Wait till you taste it! It's incredible", timestamp: "11:00 AM", read: true },
      { id: "m6", senderId: "me", text: "Now I'm curious! 😋", timestamp: "11:30 AM", read: true },
      { id: "m7", senderId: "abena", text: "Let's do brunch this weekend!", timestamp: "2 hr ago", read: false },
    ],
  },
  {
    id: "conv-yaw",
    contact: CONTACTS[4],
    unreadCount: 0,
    lastMessage: "Perfect! I'll help you set it up tomorrow",
    lastTimestamp: "1 hr ago",
    messages: [
      { id: "m1", senderId: "me", text: "Hey Yaw! Need your tech expertise", timestamp: "2:00 PM", read: true },
      { id: "m2", senderId: "yaw", text: "What's up, Ama? Fire away!", timestamp: "2:05 PM", read: true },
      { id: "m3", senderId: "me", text: "My laptop is acting up, keeps freezing", timestamp: "2:10 PM", read: true },
      { id: "m4", senderId: "yaw", text: "Have you tried restarting it first? Classic fix 😄", timestamp: "2:15 PM", read: true },
      { id: "m5", senderId: "me", text: "Yes, but it still happens. Any other ideas?", timestamp: "2:20 PM", read: true },
      { id: "m6", senderId: "yaw", text: "Let's check for updates and maybe clear some space", timestamp: "2:30 PM", read: true },
      { id: "m7", senderId: "yaw", text: "Perfect! I'll help you set it up tomorrow", timestamp: "1 hr ago", read: true },
    ],
  },
  {
    id: "conv-efua",
    contact: CONTACTS[5],
    unreadCount: 4,
    lastMessage: "Meditation session at 6 AM tomorrow? 🧘‍♀️",
    lastTimestamp: "30 min ago",
    messages: [
      { id: "m1", senderId: "efua", text: "Good morning, Ama! ☀️", timestamp: "6:00 AM", read: true },
      { id: "m2", senderId: "me", text: "Good morning Efua! How are you today?", timestamp: "6:30 AM", read: true },
      { id: "m3", senderId: "efua", text: "Feeling completely at peace ✨", timestamp: "6:45 AM", read: true },
      { id: "m4", senderId: "me", text: "That's wonderful to hear!", timestamp: "7:00 AM", read: true },
      { id: "m5", senderId: "efua", text: "Have you tried that meditation I recommended?", timestamp: "8:00 AM", read: false },
      { id: "m6", senderId: "efua", text: "It really helps with stress", timestamp: "8:05 AM", read: false },
      { id: "m7", senderId: "efua", text: "Meditation session at 6 AM tomorrow? 🧘‍♀️", timestamp: "30 min ago", read: false },
    ],
  },
]

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "message",
    title: "New message from Kwame",
    description: "See you there! 🕒",
    timestamp: "Just now",
    read: false,
  },
  {
    id: "n2",
    type: "joined",
    title: "Kofi Boateng just joined YO!",
    description: "Your friend is now on YO!",
    timestamp: "2 min ago",
    read: false,
  },
  {
    id: "n3",
    type: "message",
    title: "New message from Efua",
    description: "Meditation session at 6 AM tomorrow? 🧘‍♀️",
    timestamp: "30 min ago",
    read: false,
  },
  {
    id: "n4",
    type: "missed_call",
    title: "Missed call from Zara Mensah",
    description: "She tried to reach you",
    timestamp: "1 hr ago",
    read: true,
  },
  {
    id: "n5",
    type: "joined",
    title: "Abena Frimpong just joined YO!",
    description: "Your friend is now on YO!",
    timestamp: "2 hr ago",
    read: true,
  },
  {
    id: "n6",
    type: "message",
    title: "New message from Abena",
    description: "Let's do brunch this weekend!",
    timestamp: "2 hr ago",
    read: true,
  },
  {
    id: "n7",
    type: "missed_call",
    title: "Missed call from Yaw Darko",
    description: "He tried to reach you",
    timestamp: "Yesterday",
    read: true,
  },
  {
    id: "n8",
    type: "joined",
    title: "Efua Asare just joined YO!",
    description: "Your friend is now on YO!",
    timestamp: "Yesterday",
    read: true,
  },
]
